# Generated by Django 6.0.5 on 2026-06-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='missed',
            field=models.BooleanField(default=False),
        ),
    ]
