# Generated by Django 6.0.5 on 2026-06-15 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habitlog_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(default=datetime.time(6, 0)),
            preserve_default=False,
        ),
    ]
