# Generated by Django 6.0.5 on 2026-07-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_passwordotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
