# Generated by Django 6.0.5 on 2026-07-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_profile_gender_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='habit_time',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='status',
        ),
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(default='Health', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(default='Daily', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
