# Generated by Django 6.0.5 on 2026-07-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_habit_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'log_date'), name='unique_habit_log'),
        ),
    ]
