# Generated by Django 6.0.5 on 2026-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_habitlog_unique_habit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_type', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Nut', 'Nut & Seeds'), ('Beverage', 'Beverage'), ('Snack', 'Snack'), ('Fast Food', 'Fast Food'), ('Dessert', 'Dessert')], max_length=30)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Any', 'Any Time')], max_length=20)),
                ('diet_type', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non Vegetarian'), ('Vegan', 'Vegan')], max_length=20)),
                ('goal', models.CharField(choices=[('Weight Gain', 'Weight Gain'), ('Weight Loss', 'Weight Loss'), ('Maintain', 'Maintain')], max_length=20)),
                ('serving_size', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sugar', models.FloatField()),
            ],
        ),
    ]
