# Generated by Django 6.0.5 on 2026-07-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sugar',
        ),
    ]
