# Generated by Django 6.0.5 on 2026-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_remove_food_carbs_remove_food_fat_remove_food_fiber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='health_score',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Good'), (3, '⭐⭐⭐ Average'), (2, '⭐⭐ Poor'), (1, '⭐ Avoid')], default=3),
        ),
    ]
