# Generated by Django 6.0.5 on 2026-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_food_health_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('medicine_name', models.TextField()),
                ('dosage', models.CharField(max_length=200)),
                ('precautions', models.TextField()),
                ('symptoms', models.TextField()),
                ('home_remedy', models.TextField()),
                ('foods_to_eat', models.TextField()),
                ('foods_to_avoid', models.TextField()),
                ('consult_doctor', models.TextField()),
            ],
        ),
    ]
